### ISSUE TITLE
Problems with jQuery 3.0.0

### ISSUE THREAD

**Issue by nkolban** [mar10/jquery-ui-contextmenu#103]
I have installed jQuery 3.0.0 and it appears to break this module.  The menu now appears at the top left of my browser window and there is an error in the browser console log:

<img width="304" alt="2016-06-23_15-03-53" src="https://cloud.githubusercontent.com/assets/3421732/16318221/c3d647a4-3953-11e6-956b-57bd118e26d7.png">

**Comment by mar10** [comment]
Which versions of jQuey UI and ui-contextmenu are you using?

**Comment by nkolban** [comment]
Howdy, I am using jQuery-UI 1.11.4 and v1.12.0 of ui-contextmenu.  To the best of my knowledge, I am using the latest versions of all packages.  I tested the solution at a pre jQuery 3.0.0 release and the only change I made was to jQuery 3.0.0 and it was then that ui-contextmenu started acting up.

**Comment by mar10** [comment]
I could the problem with jQuery 3.0 / jQuery UI 1.11.4.

However it works with jQuery 3.0 / jQuery UI 1.12.rc.2.
It also works with jQuery 3.0 + jQuery-Migrate 3 / jQuery UI 1.11.4

From https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/ :

> Compatibility with jQuery UI and jQuery Mobile
While most things will work, there are a few issues that jQuery UI and jQuery Mobile will be addressing in upcoming releases. If you find an issue, keep in mind that it may already be addressed upstream and using the jQuery Migrate 3.0 plugin should fix it. Expect releases soon.
