### ISSUE TITLE
Keyboard control of context menus

### ISSUE THREAD

**Issue by maasha** [mar10/jquery-ui-contextmenu#105]
I can't get the online demos to work with keyboard control (Chrome and IE11). First of all, how is this supposed to work?

I tried to mouse-over of an elements with context menu and hit e.g. ctrl+x in order to cut. Nothing happens.

Alternatively, I selected an element with mouse left-click or tab and then hit e.g. ctrl+x in order to cut. Nothing happens.

Lastly, I right-clicked an element to open the context menu, and then hit e.g. ctrl+x -> Nothing happens.

**Comment by mar10** [comment]
This is only a sample for a menu that modifies it's entries depending on a context.
If you right click on 'AAA' it will display 'Copy "AAA"'.
Then, when you selected that, and right click anywhere again, it will also enable an entry 'Paste "AAA"', that's all - there is no implementation of Copy/Paste functionality!

**Comment by maasha** [comment]
Oh, I thought that there was keyboard handling. Do we have a working example somewhere with keyboard handling and context menu?

**Comment by mar10** [comment]
I created this plugin as a supplemental for Fancytree. Sample here:
http://wwwendt.de/tech/fancytree/demo/sample-3rd-ui-contextmenu.html

Keyboard control is completely unrelated to a context menu, but this example combines both:
http://wwwendt.de/tech/fancytree/demo/sample-multi-ext.html
Here the context menu and the keyboard handler generate custom events, so the commands can be handled at one single place.
(Note: the demo is currently partly broken: mar10/fancytree#621)
