### ISSUE TITLE
Error on right-click with fancytree

### ISSUE THREAD

**Issue by scottnc27603** [mar10/jquery-ui-contextmenu#107]
Uncaught TypeError: ((o.event.special[g.origType] || (intermediate value)).handle || g.handler).apply is not a function  

I've successfully added the dnd, and edit extensions, but when I add the contextmenu after the fancytree is created with the contextmenu call everything seems ok until I right click on a treeview item.  
`      $sceneTreeDiv.contextmenu( {
         "delegate": ".hasmenu",
         "menu": [
            { "title": "Copy", "cmd": "copy", "uiIcon": "ui-icon-copy" },
            { "title": "Paste", "cmd": "paste", "uiIcon": "ui-icon-clipboard", "disabled": false },
            { "title": "----"},
            { "title": "Edit", "cmd": "edit", "uiIcon": "ui-icon-pencil", "disabled": true },
            { "title": "Delete", "cmd": "delete", "uiIcon": "ui-icon-trash", "disabled": true },
         ]
      } );`

I've taken all of the events for the menu out to try to find the problem, but I'm still getting the error.

I've also created a sample application from the fancytree repo that is working, but the documentation suggests using this repo instead of the 3rd party context menu.  Has anyone seen this problem and knows what a solution might be?

**Comment by mar10** [comment]
This example could help
http://wwwendt.de/tech/fancytree/demo/sample-3rd-ui-contextmenu.html
