### ISSUE TITLE
Bump AMD compatibility to jquery-ui 1.12 (drop 1.11 support)

### ISSUE THREAD

**Issue by targos** [mar10/jquery-ui-contextmenu#108]
jquery-ui 1.12 [changed its directory structure](https://github.com/jquery/jquery-ui/commit/8140d0c9017a1060155662a229fec49e82530117) and it is not possible to load jquery-ui-contextmenu with requirejs anymore.
Unless I'm misunderstanding something, the AMD wrapper should now be `define([ "jquery", "jquery-ui/widgets/menu" ], factory );`

**Comment by mar10** [comment]
It's probably ok to push the requirements to jQuery UI 1.12, but that would break compatibility with 1.11 I guess?
(ref: https://learn.jquery.com/jquery-ui/environments/amd/ )
Are you aware of a way to have this backwards compatible?

Another aspect here: mar10/fancytree#603

**Comment by targos** [comment]
> that would break compatibility with 1.11 I guess

Yes. I don't know of a workaround to keep backwards compatibility.

**Comment by gauravbhavsar** [comment]
I seen [demo](http://wwwendt.de/tech/demo/jquery-contextmenu/demo/index-1-12.html) which works with jQuery UI 1.12, but its fail to load menu.js in my case. because of this `define(["jquery", "jquery-ui/menu"], factory);`

**Comment by mar10** [comment]
@targos Could you test with
```js
define([ "jquery", "jquery-ui/ui/widgets/menu" ], factory );
```
(note the additional `../ui/..`, according to http://jqueryui.com/upgrade-guide/1.12/#official-package-on-npm.)

If you confirm that it works, I will release a new version

**Comment by targos** [comment]
@mar10 works fine. I worked around the issue with a map entry in my requirejs config, but it would be nice to be able to remove this ;)
```js
    map: {
        'components/ui-contextmenu/jquery.ui-contextmenu.min': {
            'jquery-ui/menu': 'jquery-ui/ui/widgets/menu'
        }
    }
```

**Comment by mar10** [comment]
thanks!

**Comment by crystalfp** [comment]
Thanks targos!
Your suggestion to use Require JS `map` solved the issue. Just to recap (and maybe to put it somewhere in the tip and tricks section). If your application already loads `jquery-ui` library you don't need to have also the jQueryUI `menu.js` library. Simply add a map section in `requirejs.config` this way (the `paths` section is how I setup my libraries):
```
requirejs.config({
    paths: {
        ...
	"jquery-ui": "jquery-ui.min",
	"contextmenu": "jquery.ui-contextmenu.min",
	...
    },
   map: {
        'contextmenu': {
            'jquery-ui/ui/widgets/menu': 'jquery-ui'
        }
    }
});
```
