### ISSUE TITLE
AMD: isn't jquery-ui dependency sufficient?

### ISSUE THREAD

**Issue by crystalfp** [mar10/jquery-ui-contextmenu#112]
I'm integrating your contextmenu inside an application that already use jQuery-UI 1.12.1
To avoid unneeded duplications of jQuery-UI modules, I had to edit jquery.ui-contextmenu.min.js (1.14.1-0) and change "jquery-ui/ui/widgets/menu" to "jquery-ui" in define().
Is there any reason why the former is used and not the latter? To me seems that contextmenu will always been used in applications that already provide the full jQuery-UI.
I'm not very fluent in RequireJS, so I don't know if this change can be avoided by some RequireJS magic.
Thanks for clarifying (or fixing)!
mario

**Comment by crystalfp** [comment]
If I try to use RequireJS bundles this way:
```
bundles: {
        'jquery-ui': ["jquery-ui/ui/widgets/menu"]
}
```
I receive `Uncaught Error: Load timeout for modules: jquery-ui/ui/widgets/menu`
So seems the only option is to edit `jquery.ui-contextmenu.min.js`

**Comment by mar10** [comment]
I have to admit that I don't use AMD myself, but the feature was requested here, and seems to work at least for some people: #108 
Maybe you should comment there, if you have objections.
Here is some additional information: https://learn.jquery.com/jquery-ui/environments/amd/ (note: related to 1.11 which had a slightly different directory structure)
