### ISSUE TITLE
Cannot access "extraData" in "select()" callback

### ISSUE THREAD

**Issue by jnbarchan** [mar10/jquery-ui-contextmenu#114]
An external framework is sending me a "right-click" event.  I therefore use programmatic `contextmenu("open", event, extraData)` to open the context menu.  I need to pass the framework's object through to the contextmenu's callbacks.  This works in the `beforeOpen()` handler, but not in the `select()` handler, which I need.  Is this a "bug" or an "enhancement" or what is the intended behaviour?

Skeleton:

```
frameworkObject.onRightClick(event)
{
  $(document).contextmenu("open", event, { mydata: this; });
}

contextMenu = {
  beforeOpen: function (event, ui)
  {
    // ui.extraData.mydata is nicely available here
  },

  select: function (event, ui)
  {
    // ui.extraData is **not** available here
    // ui.item.data() does not help here either
  }
}
```
If it makes any difference, I am using IE 11.

**Comment by mar10** [comment]
I'd call it an enhancement, but anyway: should be fixed ;-)
The extraData will be the same instance now, throughout the event sequence, so we can pass on custom data.

**Comment by jnbarchan** [comment]
I don't know whether it's etiquette not to say "thank you" here, but thank you for your extremely prompt fix!

**Comment by mar10** [comment]
You're welcome. Feedback is always apreciated :)
I make a new relerase soon...
