### ISSUE TITLE
Generate a version where @VERSION is replaced by the current version number

### ISSUE THREAD

**Issue by kozi** [mar10/jquery-ui-contextmenu#117]
In all files I downloaded the *.js files do not contain the version number. 

```javascript
// ...
$.widget("moogle.contextmenu", {
	version: "@VERSION",
	options: {
		addClass: "ui-contextmenu",  // Add this class to the outer <ul>
		autoFocus: false,     // Set keyboard focus to first entry on open
// ...
```
In your implementation you rely on a correct version numbers in ```$.ui.menu.version```. If someone builds jquery-ui on his own this property is also filled with ```@VERSION```.

**Comment by mar10** [comment]
The minified script now contains the build version.
(Maybe we should switch to a separate /dist folder, with a copy of the non-minified version later, but this would break compatibility und would require a major bump)

**Comment by sturdeac** [comment]
Sorry to revive this issue, but even with the minified version I'm still having an issue similar to @kozi. $.ui.menu.version returns "@VERSION" and in line 25 relies on $.ui.menu.version to return a valid version number. Is there a workaround for this that I can use?

**Comment by mar10** [comment]
`$.ui.menu.version` is the version of the jQuery-UI menu widget (1.12.1 for the latest release), not jquery-ui-contextmenu.
It is required to detect the different markup styles.
Are you using an official release?

Anyway, I don't actively maintain this project anymore. You probably have to patch it locally.
