### ISSUE TITLE
Need to be able to change menu entry (icon) dynamically

### ISSUE THREAD

**Issue by jnbarchan** [mar10/jquery-ui-contextmenu#119]
I need to be able to change a menu entry's icon _dynamically_, and the implementation of `setEntry(cmd, data)` makes this very tricky.

I have what I would have thought is a not uncommon requirement: my context menu has a series of "state" (sub-)entries where just one of them can be selected.  The one currently selected must be shown as such.  I am going to put a "check mark" icon against the one selected.

```
menu: [
  ... other entries ...
  { title: "Line Style", children: [
      { title: "Manhattan", cmd: "manhattan" },
      { title: "Metro", cmd: "metro" },
      { title: "One Side", cmd: "oneSide" },
      { title: "Orthogonal", cmd: "orthogonal" }
    ]
  }
  ... other entries ...
],
```
Each time before opening the menu I'm going to need to set icons against each of those entries, so that the one whose `cmd` is the currently selected line style has a "check mark" and all the rest do not.  I'd like to go:

```
  beforeOpen: function (evt, ui)
  {
    var lineStyles = ["manhattan", "metro", "oneSide", "orthogonal"];
    $.each(lineStyles, function () {
      $(document).contextmenu(
        "setEntry",
        this,
        { uiIcon: (this == currentStyle) ? "ui-icon-check" : "ui-icon-blank"}
      );
  };
```
But I cannot do that: `setEntry` requires I pass in the complete menu entry (with `uiIcon:` in it).  And I do not have the complete, original menu entry to hand.

The problem is it is not easy for me to get at the right menu entries in my original `menu[]` array.  I am going to have to write code to go through `menu[]`, including recursively descending into any `children[]`, to find each `cmd` value.  From that I can then pass the kind of entry `setEntry` wants which can have `uiIcon` attribute.  That is what I will have to do for now.

But it gets worse.  I may have disabled certain entries dynamically, via `"enableEntry", cmd, false`, or any of the other methods you offer.  That changed information is not present in the original `menu[]` array.  In order to change the icon, I have to pass in a complete new entry, so to get it right I need really to gather all that information somehow and "replay" it against the newly-created menu item.

Please let me know if you think there is any simpler approach.  Otherwise --- and I see the code is complex for setting the icon during creation --- would you like to refactor it so that you can offer, say, a dedicated `setEntryIcon()` method?  (More generally you could think about a `mergeEntry(cmd, { ...})` method, but then you have to think about how to _remove_ attributes too...)  Would you just like to provide a "find cmd in options menu[]" to at least save users having to write that bit?

Many thanks!

**Comment by mar10** [comment]
(see also #36 )
Icons could be switched directly using plain jQuery, but I agree that a setEntryIcon(cmd, icon) helper would be convenient.
We could also add a getEntry() method that returns the `div.ui-menu-item-wrapper`.

What you are *really* describing however, is support for radio groups . It would be interesting to have a concept for this (and checkboxes). For example should checkbox icons be separate from normal icons? Keyboard support? Hoe to define this in the entry definitions and what APIs should be added...

**Comment by jnbarchan** [comment]
1. I would be content to set icon via explicit jQuery instead.  However (IIRC, I'm not at work) it's not obvious how to get at the individual menu items?  Could you post an example (doesn't have to be perfect, just show how you get to the jQuery menu item)?

2. At least for my part, I think providing an interface to checkbox/radio groups on context menu is unnecessarily complex.  User putting the required logic into `beforeOpen()` is quite adequate in this situation --- so long as I know how to get at icon, as per above.

3. Instead of dedicated helper function for each thing one might want to change in a menu item --- icon, tooltip, enablement, ... --- the way I see other JS packages doing this is a single function which takes an object with whatever desired attributes, e.g. `updateMenuItem(cmd, { icon: ..., tooltip: ... })`, and similarly for top-level menu.  Code should be shareable against those options currently at creation time; you just need to factor out what you currently have at creation-only time.  The one problem is how to allow _deletion_ of a property this way: I can't recall whether you can detect `{ property: undefined }` being passed in or whether in that case you simply don't see that `property` at all (using `null` instead is a possibility).

**Comment by mar10** [comment]
Depending on the jQuery-UI version s.th like this should work:
```js
beforeOpen: function(event, ui) {
    var $menu = ui.menu;

    $menu.find("li[data-command=paste] span.ui-icon")
        .removeClass()
        .addClass("ui-icon ui-icon-copy");
}
```

Ad 3.: a similar issue exists and could be discussed here: #36 
I re-opened it

**Comment by jnbarchan** [comment]
>  `$menu.find("li[data-command=paste] span.ui-icon")`

Perfect, thank you for your time!  (You should supply that publicly as `getMenuItem(cmd)` !)
