### ISSUE TITLE
Punctuation characters in "cmd" cause JavaScript error

### ISSUE THREAD

**Issue by jnbarchan** [mar10/jquery-ui-contextmenu#120]
I have menu entries for zooming, like `zoom-50%`.

When my code calls, for example, `$(document).contextmenu("enableEntry", cmd, flag)` with `cmd == zoom-50%`, your function

	/** Return ui-menu entry (<LI> tag). */
	_getMenuEntry: function(cmd) {
		return this.$menu.find("li[data-command=" + cmd + "]");
	},

generates error `JavaScript runtime error: Syntax error, unrecognized expression: li[data-command=zoom-50%]`.

You should be quoting `cmd` when passing in a selector, e.g. `this.$menu.find("li[data-command='" + cmd + "']")`, to allow for various potential special characters in `cmd`.  I do not know whether there are other code routes which would fall foul of this too.

Obviously my workaround is to rename that command to `zoom-50`, which works, but it would be nice if this restriction was not necessary.

**Comment by mar10** [comment]
Thanks for suggesting.
However currently I don't think it is worth the effort, and it is acceptable to impose some restrictions on the `cmd` keyword.
May be we'll re-open this when it get's some upvotes or patches from the community ...

**Comment by jnbarchan** [comment]
IMHO this is the wrong decision.  It's one thing for something to "not work", but another thing if it causes a runtime error.  In terms of effort, all you have to do is put double-quotes round the argument, which I don't think can break any existing clients, viz.

`return this.$menu.find("li[data-command=\"" + cmd + "\"]");`

_However_, I also think this is your code and you can do or not do anything you like!  Thanks for a good component.

**Comment by mar10** [comment]
> I do not know whether there are other code routes which would fall foul of this too.

So do I ;-) So if you want to take the effort, check for corner cases and provide a patch (including tests), I am still open for this.
