### ISSUE TITLE
Plugin loading error reading jquery-ui property

### ISSUE THREAD

**Issue by brunoflmg** [mar10/jquery-ui-contextmenu#121]
I'm using the plugin on a project and there sometimes, during page load, the plugin raise an Exception as describe below. 

My script tags used.

```
<head>
    <script type="text/javascript" src="/js/jquery-1.11.1.min.js"></script>
    <link type="text/css" rel="stylesheet" href="/css/bootstrap.min.css">
    <script type="text/javascript" id="jquery-ui-lib" src="/js/jquery-ui/jquery-ui.min.js"></script>
    <link type="text/css" rel="stylesheet" id="jquery-ui-css" href="/js/jquery-ui/jquery-ui.min.css">
    <script type="text/javascript" src="/js/jquery.ui-contextmenu.min.js"></script>
    <script type="text/javascript" src="/js/context-menu.js"></script>
</head>
```

JS code inside context-menu.js file:

```
$(function() {
    // Apply jquery ui context menu to any element on the page
    $(document).contextmenu({
        delegate: "body",
        autoFocus: true,
        preventContextMenuForPopup: true,
        preventSelect: true,
        taphold: true,
        menu: [{
            title: "Cut",
            cmd: "cut",
            uiIcon: "ui-icon-scissors",
            disabled: function(opt, e) {
                return $(e.target).is('body') ? true : false;
            }
        }, {
            title: "Copy",
            cmd: "copy",
            uiIcon: "ui-icon-copy",
            disabled: function(opt, e) {
                return $(e.target).is('body') ? true : false;
            }
        }, {
            title: "Paste",
            cmd: "paste",
            uiIcon: "ui-icon-clipboard",
            disabled: function(opt, e) {
                return checkElementCopied();
            }
        }]
    });
});
```

Note: different from documentation... I've assigned the body tag as delegate selector. I'm not sure if it is not recommend, but it's working.

The problem is... sometimes there's an exception during page load: **Uncaught TypeError: Cannot read property 'menu' of undefined**. Follow the piece of code where the Exception is raising:

```
var supportSelectstart = "onselectstart" in document.createElement("div"),
	match = **$.ui.menu.version.match**(/^(\d)\.(\d+)/),
	uiVersion = {
		major: parseInt(match[1], 10),
		minor: parseInt(match[2], 10)
	},
	isLTE110 = ( uiVersion.major < 2 && uiVersion.minor <= 10 ),
	isLTE111 = ( uiVersion.major < 2 && uiVersion.minor <= 11 );
```

Maybe this exception is raising because the jquery-ui isn't ready yet. It will be a good idea if we have a fallback method for the context-menu plugin or someway to start everything after check if jquery-ui was already loaded, if possible.

Browser used: Chrome v.58

**Comment by brunoflmg** [comment]
I've found a temporary solution...

After modified the code as described bellow the issue is now solved, but I suggest to create a way to avoid this exception:

- Commented the ui version regex check.
- Forced the major and minor jquery ui version.

```
var supportSelectstart = "onselectstart" in document.createElement("div"),
	// match = $.ui.menu.version.match(/^(\d)\.(\d+)/),
	uiVersion = {
		major: 1,
		minor: 11
	},
	isLTE110 = ( uiVersion.major < 2 && uiVersion.minor <= 10 ),
	isLTE111 = ( uiVersion.major < 2 && uiVersion.minor <= 11 );
```

**Comment by mar10** [comment]
I have  not seen this error before. It seems like `$` is defined, but `$.ui` is not. So `query-1.11.1.min.js` was loaded, but `jquery-ui.min.js` was not.
You could add some logging there, to verify.
I also noticed an `id="jquery-ui-lib"` attribute: is there any dynamic magic happening to modify or add header script tags?

**Comment by brunoflmg** [comment]
Answering your question... yes. Those script tags and link tags are added dynamically.

I found a way to avoid this issue. Maybe it will be a good idea to implement something like this in your plugin before start it. Before this part maybe **var supportSelectstart = "onselectstart" in document.createElement("div") ... **

```
/**
 * This var will indicate if jquery ui is already loaded or not
 */
var jqueryUiIsLoaded;

/**
 * Add context menu to website builder
 */
function addContextMenuToBuilder() {
    jqueryUiIsLoaded = setTimeout(function(){
        // check if jquery ui was loaded
        if ($.ui) {
            // bind contextmenu event to document
            addContextMenu();

            // stop this check to continue executing
            stopChecking();
        }
    }, 300);
}

/**
 * Stop to look for jquery ui
 */
function stopChecking() {
    clearTimeout(jqueryUiIsLoaded);
}

/**
 * Bind contextmenu event to document
 */
function addContextMenu() {
    // apply jquery ui context menu to any element on the page
    $(document).contextmenu({
        delegate: "body",
        autoFocus: true,
        preventContextMenuForPopup: true,
        preventSelect: true,
        taphold: true,
        menu: [{
            title: "Cut",
            cmd: "cut",
            uiIcon: "ui-icon-scissors",
        }, {
            title: "Copy",
            cmd: "copy",
            uiIcon: "ui-icon-copy",
        }, {
            title: "Paste",
            cmd: "paste",
            uiIcon: "ui-icon-clipboard",
        }]
    });
}

/**
 * Jquery page ready listener function
 */
$(function() {
    addContextMenuToBuilder();
});
```

**Comment by mar10** [comment]
> Maybe it will be a good idea to implement something like this in your plugin before start it.

jQuery UI is simply a requirement for this plugin, and don't think that it is the responsibility of plugins to wait for all dependencies to be loaded.
The root problem seems to be that you initialize on page load
```js
$(function() {
    ...
 }
```
which is too early in your case. Instead you should initialize in the ready-event (or similar) of your loader.
Most AMD loaders, like [requirejs](http://requirejs.org/docs/start.html) offer callbacks or other mechanisms for this.
