### ISSUE TITLE
How to use ContextMenu with HTML

### ISSUE THREAD

**Issue by jt4000** [mar10/jquery-ui-contextmenu#124]
![123](https://user-images.githubusercontent.com/14993569/33876479-f423f18a-df25-11e7-943b-2cdc034e5291.png)

Questions:
Is there a sample about how to apply this contextmenu with "Initialize menu from an existing element" by using jsfiddle or similar?

Info:
- https://github.com/mar10/jquery-ui-contextmenu
- https://github.com/mar10/jquery-ui-contextmenu/wiki#initialize-menu-from-an-existing-ul-element

**Comment by mar10** [comment]
There is no fiddle, but this page has an example at the bottom
http://wwwendt.de/tech/demo/jquery-contextmenu/demo/index-1-12.html
