### ISSUE TITLE
Custom Icon issue

### ISSUE THREAD

**Issue by vishalsingh119** [mar10/jquery-ui-contextmenu#125]
how to add the custom icon like icomoon and font awesome

**Comment by mar10** [comment]
The `uiIcon` option only generates standard jQuery UI icons. But the `title` option accepts arbitrary  HTML markup, so it should be possible to insert custom `<span>` or `<i>` elements.
(Note that jquery-ui-contextmenu is only a wrapper for [jQuery UI Menu](http://jqueryui.com/menu/)).
