### ISSUE TITLE
open an existing menu by left click

### ISSUE THREAD

**Issue by joankent** [mar10/jquery-ui-contextmenu#127]
hi, how can open an existing menu by left click on an external button, like this?

$("#containerMenu").contextmenu({
	delegate: "menuDivName",
	preventContextMenuForPopup: true,
	menu: [
		{title: "option1", cmd: "Fanasa", uiIcon: "ui-icon-folder-open", disabled: false },
		{title: "option2", cmd: "Marzam", uiIcon: "ui-icon-folder-open", disabled: false }
	],
	beforeOpen: function(event, ui) {					
	},
	select: function(event, ui) {
		console.log(ui.cmd);
	}
});

$("#triggerPopupBtn").click(function(){
       $(document).contextmenu("open", $("#containerMenu"), {foo: "bar"});
});

I try to implement this example:
http://wwwendt.de/tech/demo/jquery-contextmenu/demo/index-1-12.html

but your code is something different :(

can you help me please?

thanks.

**Comment by mar10** [comment]
Please give some more information, what you tried, and what errors you see.
A jsFiddle, Plunkr or CodePen would be helpful as well.
Thanks
