### ISSUE TITLE
jquery-migrate-3.0.0.js warning

### ISSUE THREAD

**Issue by wanderleihuttel** [mar10/jquery-ui-contextmenu#130]
In the line 478 is necessary to remove the method removeAttr() and change with attr() for jquery migrate no show warnings.
````
from:
$entryLi.removeAttr("title");

to:
$entryLi.attr("title", "");
````

https://github.com/jquery/jquery-migrate/blob/master/warnings.md

JQMIGRATE: jQuery.fn.removeAttr no longer sets boolean properties
Cause: Prior to jQuery 3.0, using .removeAttr() on a boolean attribute such as checked, selected, or readonly would also set the corresponding named property to false. This behavior was required for ancient versions of Internet Explorer but is not correct for modern browsers because the attribute represents the initial value and the property represents the current (dynamic) value.

Solution: It is almost always a mistake to use .removeAttr( "checked" ) on a DOM element. The only time it might be useful is if the DOM is later going to be serialized back to an HTML string. In all other cases, .prop( "checked", false ) should be used instead.

**Comment by mar10** [comment]
"title" is not a boolean attribute, but a string. Does jqmigrate really emit a warning?

**Comment by mar10** [comment]
Can give some more details, how you see this warning, especiall the HTML source with the `<script>` include statements please.

**Comment by wanderleihuttel** [comment]
Hello @mar10! 
I guess was my mistake.
I was migrating my project to jquery 3.0 and I was using jquery 2.2.4 when the warning occurred. Now is not showing anymore.

**Comment by mar10** [comment]
thanks for the update.
