### ISSUE TITLE
What parameter in .contextmenu is used to indicate that context menu should appear on hover?

### ISSUE THREAD

**Issue by nadavb** [mar10/jquery-ui-contextmenu#131]
What parameter in .contextmenu is used to indicate that context menu should appear on hover?

**Comment by mar10** [comment]
There is no such parameter to open a menu on hover. You have to listen for such events and trigger the menu manually:
https://github.com/mar10/jquery-ui-contextmenu/wiki#howto-trigger-the-menu-on-custom-events
