### ISSUE TITLE
Blur is fired even when I moved between context menu items

### ISSUE THREAD

**Issue by nadavb** [mar10/jquery-ui-contextmenu#133]
In the docs it says:
```
blur(event, ui)
Triggered when the menu loses focus (original jQuery UI Menu event).
```
But I get blur fired even when I move between menu items in the context menu.

**Comment by mar10** [comment]
Hi,
this context menu plugin is only a small wrapper around the original jQuery UI Menu widget.
I guess it works as designed:
http://api.jqueryui.com/menu/#event-blur
Otherwise, please look there.
