### ISSUE TITLE
Can't create two contextmenu for the same wrapper element (document)

### ISSUE THREAD

**Issue by nadavb** [mar10/jquery-ui-contextmenu#135]
I'm having problems creating two context menus.
I invoke `$(document).contextmenu`  with delegate to my element id.
after a while, I create another `$(document).contextmenu` to a different element id.

And then only the first one I created works, and then other one doesn't.

**Comment by mar10** [comment]
This is explained in the wiki (at the bottom)

**Comment by nadavb** [comment]
Works great. Thank you for the support!
