### ISSUE TITLE
menu item title dash "-" is not showing, but showing as seperator

### ISSUE THREAD

**Issue by nadavb** [mar10/jquery-ui-contextmenu#136]
I'm trying to set a title simply to one dash.
Instead of showing the dash, it shows a seperator.

How do I show an html of dash only?

**Comment by nadavb** [comment]
[Here](https://api.jqueryui.com/menu/) I see mention to _isDivider( item ) that you can override to disable this strange dash-to-divider conversion. But how do I pass it via jquery-ui-contextmenu?

**Comment by mar10** [comment]
I don‘t have a simple answer , but may be you can pass &mdash; or something similar instead of a hyphen

**Comment by nadavb** [comment]
Hi @mar10, I really need to be able to pass hyphen and other kind of strings. Can you kindly see if there's a solution for that, because I still want to use jquery-ui-contextmenu.

**Comment by mar10** [comment]
Here is an [example how you may solve it](https://github.com/mar10/jquery-ui-contextmenu/commit/ac12ada8ec0ccfebc092eb6366b256027005d680):

  1. patch the library, for example to only recognize four hyphens as separator
  2. globally override the jQuery UI Menu _isDivider callback

I am not currently planning a new release though.

**Comment by nadavb** [comment]
Is there a way to to specify that a menu item should be a separator/divider without changing the titles to hyphens? i.e. by specifying some other attribute of the menu item? If that is possible, then we can remove this hyphens-to-divider scheme altogether....
