### ISSUE TITLE
Checking if a context menu is opened/closed or destroyed

### ISSUE THREAD

**Issue by ndvbd** [mar10/jquery-ui-contextmenu#140]
Is there a way to know the context menu state? open/closed/destroyed?

I am creating the context menu this way:

```
$.widget("moogle."+contextMenuFunctionName, $.moogle.contextmenu, {  });
$(document)[contextMenuFunctionName]({..... });
```

And to close or destroy it I do:
```
$(document)[contextMenuFunctionName]("close", $(selector));
$(document)[contextMenuFunctionName]("destroy", $(selector));

```
But how to check the state, so I don't close an already closed or destroyed menu?

**Comment by mar10** [comment]
Hi,
this pattern looks a bit unusual to me, have you [read the docs](https://github.com/mar10/jquery-ui-contextmenu/wiki)?
Maybe posting your question and example [at Stackoverflow](https://stackoverflow.com/questions/tagged/jquery-ui-contextmenu) yields a response.

**Comment by ndvbd** [comment]
Yes, I did, just want to know how can I query the state: if it is open, or closed or destroyed.
