### ISSUE TITLE
Typescript definitions?

### ISSUE THREAD

**Issue by crystalfp** [mar10/jquery-ui-contextmenu#141]
#129 # Expected and actual behavior
Using contextmenu in a Typescript source (with definitions loaded for jQuery and jQuery-ui) elicit the following error:
```
prj-list.ts:29:4 - error TS2345: Argument of type '{ delegate: string; autoFocus: boolean; preventContextMenuForPopup: boolean; show: boolean; hide: boolean; addClass: string; menu: { title: string; uiIcon: string; action: () => void; }[]; }' is not assignable to parameter of type 'false | EventHandlerBase<HTMLElement, ContextMenuEvent<HTMLElement, null, HTMLElement, HTMLElement>> | undefined'.
  Object literal may only specify known properties, and 'delegate' does not exist in type 'EventHandlerBase<HTMLElement, ContextMenuEvent<HTMLElement, null, HTMLElement, HTMLElement>>'.

29              delegate: ".item",
                ~~~~~~~~~~~~~~~~~
Found 1 error.
```
How to override the jQueryUI definition?

### Steps to reproduce the problem

Create the following example.ts file:
```
		$("#prj-list-view").contextmenu({
			delegate: ".item",
			autoFocus: true,
			preventContextMenuForPopup: true,
			show: false,
			hide: false,
			addClass: "popup-menu",
			closeOnWindowBlur: true,
			menu: [
				{title: "Example", uiIcon: "ui-icon-check", action: (): void => console.log("Context")},
                        ]
                 });
```
Compile it and see the error.

### Environment

  - Chrome Version 80.0.3987.132 (Official Build) (64-bit)
  - jQuery and jQuery UI versions: 3.4.1 and 1.12.1
  - ui-contextmenu version:    1.18.2-0

**Comment by crystalfp** [comment]
Horrid hack to make my source compile clear:
```
interface JQueryContextmenuItem {
	title: string;
	uiIcon: string;
	action: () => void;
	children?: JQueryContextmenuItem[];
}
interface JQueryContextmenuOptions {
	delegate: string;
	autoFocus: boolean;
	preventContextMenuForPopup: boolean;
	show: boolean;
	hide: boolean;
	addClass: string;
	closeOnWindowBlur: boolean;
	menu: JQueryContextmenuItem[];
}
interface JQueryStatic {
    (selection: string|EventTarget): JQueryStatic;
    addClass(name: string): JQueryStatic;
    removeClass(name: string): JQueryStatic;
    contextmenu(options?: JQueryContextmenuOptions): void;
}
```
I put these definitions at the beginning of my source. What I don't understand is why the `contextmenu` definition is not merged with the existing (and used) `JQueryStatic` definition. This is the reason why I had to repeat here the definitions of add/remove class.
Anyway, asking a question is always a sure way to find the answer by myself.
If you want to elaborate on this, I will be grateful.
Thanks!
mario

**Comment by mar10** [comment]
Hi, 
I did not work with TS much so far. The project does not define TS type definitions and I did not see it on DefinitelyTyped as well.
I am afraid I have to wait for contributors to fix it.

**Comment by crystalfp** [comment]
Don't worry @mar10 my workaround, I don't know why, but solved my problem. So I'm happy.
Thanks!
mario
