### ISSUE TITLE
make the setEntry API more intuitive

### ISSUE THREAD

**Issue by tponthieux** [mar10/jquery-ui-contextmenu#36]
The setEntry command should take parameter that looks more like the menu option literal. Right now the command requires a parameter to identify the menu option, and then an object that somewhat resembles the menu option.

```
$(...).contextmenu('setEntry', 'paste', {title: 'Paste link'});
```

Why not put the identifier in the menu option supplement? That way it would look more like the menu option literal provided in the menu array.

```
$(...).contextmenu('setEntry', {cmd: 'paste', title: 'Paste link'});
```

If the value for cmd doesn't match anything in the menu array, it could add a new menu option. 

While we're at it, why call the menu option identifier cmd? The value of cmd isn't a command, it's a string ('paste'). It should be called something that reflects its purpose as a unique identifier. How about name or id?

**Comment by mar10** [comment]
Not currently on my list until I 
a) see some up votes by the community, or
b) get really bored

**Comment by jnbarchan** [comment]
1. 
> $(...).contextmenu('setEntry', 'paste', {title: 'Paste link'});
> versus 
> $(...).contextmenu('setEntry', {cmd: 'paste', title: 'Paste link'});
No!  Existing way is right.  `cmd` is needed to find the menu entry, it's not just some arbitrary property, and needs to be dedicated parameter.  (Whether you want that syntax to _rename_ a menu entry is a different matter.)

2.
>If the value for cmd doesn't match anything in the menu array, it could add a new menu option
Nope!  Next?

3. 
> While we're at it, why call the menu option identifier cmd?
`cmd` is perfect.

The only thing which does (would be nice) need doing is:
>This means that you have to pass all properties for the new node (see #35 ).

:)

**Comment by mar10** [comment]
Started a branch here
https://github.com/mar10/jquery-ui-contextmenu/tree/refactor-setEntry
