### ISSUE TITLE
Require.js requires jquery-ui

### ISSUE THREAD

**Issue by nkolban** [mar10/jquery-ui-contextmenu#82]
I am trying to load the plugin using require.js (AMD).  Unfortunately, it gives me an error.  Looking at the source, I see the following line:

    define([ "jquery" ], factory )

which states that we have a dependency on `jquery`.  This is fine but the plugin also uses `jquery-ui` which is where `$.widget()` comes from.  I think that the plugin may need to be altered to have the following as a define:

    define([ "jquery", "jquery-ui" ], factory )

**Comment by mar10** [comment]
Comment by Kia Dabirian Tehrani

> Hello Martin
>I have now downloaded the latest release. However I still needed to modify line 15 to 

        define([ "jquery", "jquery-ui/menu" ], factory );

>. It seams that even though "jquery-ui/menu" is enough to load all the dependencies in the correct order (as can be seen in the network activity) it results in define passing $.ui.menu to the function at line 21 as the first argument. Where as that function expects the jQuery object to be passed to is on that slot
