### ISSUE TITLE
Menu option emboldens when hovering over divider above

### ISSUE THREAD

**Issue by garybarnes995** [mar10/jquery-ui-contextmenu#86]
I have added a class to the outer UL and include font-weight:normal for the class and the sub-class li:hover. This works OK except that when I hover my mouse over a divider immediately above (before) an enabled option the option text emboldens. Observed this behaviour in Chrome and Firefox.

**Comment by mar10** [comment]
I think I observed a similar effect, but didn't have the time to investigate.
It is rather a plain CSS question, unrelated to this plugin, maybe ask this on a jQuery UI forum?
(anayway, if you find a solution, let me know ;-)

**Comment by garybarnes995** [comment]
Well, for the benefit of anyone else, I can't track down the CSS issue, and the only way to stop it is to set the element style after the menu has initialised.

For example, with addClass set to add class "my-context-menu" add this after the initialisation statement:

        $(".my-context-menu li").each(function() {
            $(this).css('font-weight', 'normal');
        });
