### ISSUE TITLE
js error "TypeError: this.$menu is null"

### ISSUE THREAD

**Issue by Raf2k** [mar10/jquery-ui-contextmenu#88]
When deleting element from context menu callback (I have "Delete" context menu item), I get js error "TypeError: this.$menu is null"; Line 278.

**Comment by Raf2k** [comment]
http://jsfiddle.net/ts5eupx8/

**Comment by mar10** [comment]
I'll look into it, but you could workaround like this
```js
    select: function(event, ui) {
        setTimeout(function(){
            $(event.target).remove();
        }, 0)
    },
```

**Comment by Raf2k** [comment]
Yes, I know, but I think that this is slightly dirty solution...
