### ISSUE TITLE
context menu closes after releasing taphold

### ISSUE THREAD

**Issue by pwntester** [mar10/jquery-ui-contextmenu#89]
Hi, 

Cool plugin, thanks!
Im using it with the taphold option for tablet compatibility. On iPads the menu is closed as soon as you release the taphold to select an option.

Cheers,
A

**Comment by mar10** [comment]
Hello,

couldn't reproduce on iPad 2 here: http://wwwendt.de/tech/demo/jquery-contextmenu/demo/
Note that ui-contextmenu depends on external plugins to generate taphold events. What external plugin are you using?

**Comment by pwntester** [comment]
Im using taphold.js. I verified your testcase works and actually it works in a different part of my application so its something different. Will debug and try to find out what is closing it immediatly.

Thanks!

**Comment by mar10** [comment]
Will re-open if some details are available.
