### ISSUE TITLE
transform delegate options in object

### ISSUE THREAD

**Issue by aureltime** [mar10/jquery-ui-contextmenu#90]
Hello,

i make heavy use of this jqueryui plugin getting back elements of the menu via XHR ( it sends me back elements of the menu that i add in the DOM with a <ul> element, it sends me also the delegate string to target the wanted trigger).

The problem i have is that the number of context menu instance linked to one DOM element is limited to one. What i need is to be able, for xample) to associate one menu for ".odd" elements and another one for ".even" elements.

I would suggest to use your option object as usual but add the possibility to send delegate as an object which is similar to the option one but can modify the general options for specific delegated nodes. See the option object example below. I know that it is possible to get to this point using the beforeOpen event but 2 drawbacks 
- difficult to send back function via XHR ( PHP )
- When it is possible to use one class to identify the delegated DOM node, it seems overdue to use before Open

```javascript
{
    delegate: 
    {
        {
        trigger : ".odd",
        menu   : "#menu1"
        } , 
       {
        trigger : ".even",
        menu   : "#menu2" ,
        select: function(event, ui) {
             ...
             }
    } ,
    menu: "#othermenu",
    select: function(event, ui) {
        ...
    }
```

Thanks for you work

Aurel

**Comment by mar10** [comment]
Thanks, I added a general feature request, since your proposal would require to know all possible instances on initialization.
it may be better to allow to add and remove different meneu instances later?
Feel free to add comments here: #91.
