### ISSUE TITLE
Allow multiple menu instances per element

### ISSUE THREAD

**Issue by mar10** [mar10/jquery-ui-contextmenu#91]
It should be possible to add multiple menu instances (i.e. delegate selectors, menu definitions, handlers, ...) to one element (for example 'document')

See also #90

**Comment by aureltime** [comment]
For me, it should be possible to provide this option object at initialisation and if we can change it later with a method it would be greater.

**Comment by mar10** [comment]
A use case, where this would be useful: Several unrelated libraries/modules/plugins may want to register a global context menu based on jquery-ui-contextmenu:
```js
  $(document).contextmenu({
    delegate: ".plugin1",
    ...
  });
```
and 
```js
  $(document).contextmenu({
    delegate: ".plugin2",
    ...
  });
```
But I am not aware of a simple pattern, to implement this, since the jQuery Widget factor does prevent multiple instantiations on the same DOM element.

**Comment by mar10** [comment]
A workaround is this:
```js
	// 1. Create and register another widget that inherits directly from 
	//    jquery-ui-contextmenu:
	$.widget("mylib.contextmenu2", $.moogle.contextmenu, {});
	// 2. Now we can bind this new widget to the same DOM element without
	//    destroying a previous widget.
	$(document).contextmenu2({
		delegate: ".hasmenu2",
		menu: "#options",
		select: function(event, ui) {
			alert("select contextmenu2" + ui.cmd + " on " + ui.target.text());
		}
	});
```

**Comment by ndvbd** [comment]
@mar10 but if we use this workaround, if we have two context menus in a page, and we destroy one of them, then these lines will kill the head style, won't they?

  if (this.$headStyle) {
                this.$headStyle.remove();
                this.$headStyle = null;
            }
