### ISSUE TITLE
Ability to provide a title attribute to a menu item

### ISSUE THREAD

**Issue by aureltime** [mar10/jquery-ui-contextmenu#92]
I would like to provide a tooltip when hovering a menu item ( with title attribute) but the title attribute is already taken, i would propose to rename it "label" so the title attribute would be available,  To provide compatibility, idea would be to use title attribute for the label if no label is provided, else use the label one.

**Comment by mar10** [comment]
I don't thin, that we should rename `title`, but possibly add a new `tooltip` option (that set a title attribute)
