### ISSUE TITLE
Uncaught TypeError: this.$menu.menu is not a function

### ISSUE THREAD

**Issue by xcy7e** [mar10/jquery-ui-contextmenu#95]
The following code produces an error, which should at least be caught:

		$('ul.review_ticket_list li').contextmenu(function() {
			return false;
		});
		$('ul.review_ticket_list').contextmenu({
			delegate: 'li',
			menu: {
				title: 'Edit comment',
				cmd: 'edit',
				uiIcon: 'ui-icon-copy'
			},
			select: function(event, ui) {
				console.log(event, ui);
			}
		});

----- results in ----- 

jquery.ui-contextmenu.js:137 Uncaught TypeError: this.$menu.menu is not a function

**Comment by xcy7e** [comment]
Found the issue. The menu-property is NOT nested in an array as suggested. Anyways. You may consider catching this. But maybe not.

**Comment by mar10** [comment]
I don't think this is hi-prio and I am lazy, so closing this - open for pull requests though ;-)
