### ISSUE TITLE
Extension-wrapper for Django 

### ISSUE THREAD

**Issue by m-libbrecht** [mar10/jquery-ui-contextmenu#97]
Hello Martin.

I’d like to build an extension to the jquery.fancytree or jquery.contextmenu to be able to use both client side scripts in conjunction with Django sites that use mptt to build hierarchical trees.

![fancytree](https://cloud.githubusercontent.com/assets/8015317/9461607/0a709ee0-4b10-11e5-84a7-267dbe91c06b.png)

I’m thinking of using a request object 
, something like this:

    var  tree_changerequest = {
        source_nodes : [ {}],
        target_node : {},
        method : "",
        new_id : 0,
        response : "" }

moving from client to server in order to persist the changes at the server side and refresh the fancy tree.

Can you tell me what approach would be appropriate ?

Thanks in advance.

Mark Libbrecht

**Comment by mar10** [comment]
This question is not related to this contextmenu plugin, but to Fancytree.
And since it is no bug or feature request, Stackoverflow may be more appropriate as well.
